// This file was generated by Mendix Modeler 6.9.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package approntonotificationmodule.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the ApprontoNotificationModule module
	public static void aCr_Notification(IContext context, approntonotificationmodule.proxies.Notification _notification)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("Notification", _notification == null ? null : _notification.getMendixObject());
			Core.execute(context, "ApprontoNotificationModule.ACr_Notification", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static approntonotificationmodule.proxies.Notification dS_GetActualNotification(IContext context)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			IMendixObject result = (IMendixObject)Core.execute(context, "ApprontoNotificationModule.DS_GetActualNotification", params);
			return result == null ? null : approntonotificationmodule.proxies.Notification.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void sF_CreateNotification(IContext context, String _message, approntonotificationmodule.proxies.Enum_NotificationType _type, approntonotificationmodule.proxies.Enum_Layout _layout, Long _timeout)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("Message", _message);
			params.put("Type", _type == null ? null : _type.name());
			params.put("Layout", _layout == null ? null : _layout.name());
			params.put("Timeout", _timeout);
			Core.execute(context, "ApprontoNotificationModule.SF_CreateNotification", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static void sF_CreateNotification_Default(IContext context, String _message, approntonotificationmodule.proxies.Enum_NotificationType _type)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("Message", _message);
			params.put("Type", _type == null ? null : _type.name());
			Core.execute(context, "ApprontoNotificationModule.SF_CreateNotification_Default", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
}