// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class Datapoint
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject datapointMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.Datapoint";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		xvalue("xvalue"),
		xsortingvalue("xsortingvalue"),
		yvalue("yvalue");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Datapoint(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MyFirstModule.Datapoint"));
	}

	protected Datapoint(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject datapointMendixObject)
	{
		if (datapointMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MyFirstModule.Datapoint", datapointMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MyFirstModule.Datapoint");

		this.datapointMendixObject = datapointMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Datapoint.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static myfirstmodule.proxies.Datapoint initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.Datapoint.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static myfirstmodule.proxies.Datapoint initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.Datapoint(context, mendixObject);
	}

	public static myfirstmodule.proxies.Datapoint load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.Datapoint.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of xvalue
	 */
	public final String getxvalue()
	{
		return getxvalue(getContext());
	}

	/**
	 * @param context
	 * @return value of xvalue
	 */
	public final String getxvalue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.xvalue.toString());
	}

	/**
	 * Set value of xvalue
	 * @param xvalue
	 */
	public final void setxvalue(String xvalue)
	{
		setxvalue(getContext(), xvalue);
	}

	/**
	 * Set value of xvalue
	 * @param context
	 * @param xvalue
	 */
	public final void setxvalue(com.mendix.systemwideinterfaces.core.IContext context, String xvalue)
	{
		getMendixObject().setValue(context, MemberNames.xvalue.toString(), xvalue);
	}

	/**
	 * @return value of xsortingvalue
	 */
	public final Integer getxsortingvalue()
	{
		return getxsortingvalue(getContext());
	}

	/**
	 * @param context
	 * @return value of xsortingvalue
	 */
	public final Integer getxsortingvalue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (Integer) getMendixObject().getValue(context, MemberNames.xsortingvalue.toString());
	}

	/**
	 * Set value of xsortingvalue
	 * @param xsortingvalue
	 */
	public final void setxsortingvalue(Integer xsortingvalue)
	{
		setxsortingvalue(getContext(), xsortingvalue);
	}

	/**
	 * Set value of xsortingvalue
	 * @param context
	 * @param xsortingvalue
	 */
	public final void setxsortingvalue(com.mendix.systemwideinterfaces.core.IContext context, Integer xsortingvalue)
	{
		getMendixObject().setValue(context, MemberNames.xsortingvalue.toString(), xsortingvalue);
	}

	/**
	 * @return value of yvalue
	 */
	public final Integer getyvalue()
	{
		return getyvalue(getContext());
	}

	/**
	 * @param context
	 * @return value of yvalue
	 */
	public final Integer getyvalue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (Integer) getMendixObject().getValue(context, MemberNames.yvalue.toString());
	}

	/**
	 * Set value of yvalue
	 * @param yvalue
	 */
	public final void setyvalue(Integer yvalue)
	{
		setyvalue(getContext(), yvalue);
	}

	/**
	 * Set value of yvalue
	 * @param context
	 * @param yvalue
	 */
	public final void setyvalue(com.mendix.systemwideinterfaces.core.IContext context, Integer yvalue)
	{
		getMendixObject().setValue(context, MemberNames.yvalue.toString(), yvalue);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return datapointMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.Datapoint that = (myfirstmodule.proxies.Datapoint) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MyFirstModule.Datapoint";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
