// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class locationDetails
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject locationDetailsMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.locationDetails";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		street("street"),
		city("city"),
		state("state"),
		zip("zip");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public locationDetails(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MyFirstModule.locationDetails"));
	}

	protected locationDetails(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject locationDetailsMendixObject)
	{
		if (locationDetailsMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MyFirstModule.locationDetails", locationDetailsMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MyFirstModule.locationDetails");

		this.locationDetailsMendixObject = locationDetailsMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'locationDetails.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static myfirstmodule.proxies.locationDetails initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.locationDetails.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static myfirstmodule.proxies.locationDetails initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.locationDetails(context, mendixObject);
	}

	public static myfirstmodule.proxies.locationDetails load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.locationDetails.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of street
	 */
	public final String getstreet()
	{
		return getstreet(getContext());
	}

	/**
	 * @param context
	 * @return value of street
	 */
	public final String getstreet(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.street.toString());
	}

	/**
	 * Set value of street
	 * @param street
	 */
	public final void setstreet(String street)
	{
		setstreet(getContext(), street);
	}

	/**
	 * Set value of street
	 * @param context
	 * @param street
	 */
	public final void setstreet(com.mendix.systemwideinterfaces.core.IContext context, String street)
	{
		getMendixObject().setValue(context, MemberNames.street.toString(), street);
	}

	/**
	 * @return value of city
	 */
	public final String getcity()
	{
		return getcity(getContext());
	}

	/**
	 * @param context
	 * @return value of city
	 */
	public final String getcity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.city.toString());
	}

	/**
	 * Set value of city
	 * @param city
	 */
	public final void setcity(String city)
	{
		setcity(getContext(), city);
	}

	/**
	 * Set value of city
	 * @param context
	 * @param city
	 */
	public final void setcity(com.mendix.systemwideinterfaces.core.IContext context, String city)
	{
		getMendixObject().setValue(context, MemberNames.city.toString(), city);
	}

	/**
	 * @return value of state
	 */
	public final String getstate()
	{
		return getstate(getContext());
	}

	/**
	 * @param context
	 * @return value of state
	 */
	public final String getstate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.state.toString());
	}

	/**
	 * Set value of state
	 * @param state
	 */
	public final void setstate(String state)
	{
		setstate(getContext(), state);
	}

	/**
	 * Set value of state
	 * @param context
	 * @param state
	 */
	public final void setstate(com.mendix.systemwideinterfaces.core.IContext context, String state)
	{
		getMendixObject().setValue(context, MemberNames.state.toString(), state);
	}

	/**
	 * @return value of zip
	 */
	public final String getzip()
	{
		return getzip(getContext());
	}

	/**
	 * @param context
	 * @return value of zip
	 */
	public final String getzip(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.zip.toString());
	}

	/**
	 * Set value of zip
	 * @param zip
	 */
	public final void setzip(String zip)
	{
		setzip(getContext(), zip);
	}

	/**
	 * Set value of zip
	 * @param context
	 * @param zip
	 */
	public final void setzip(com.mendix.systemwideinterfaces.core.IContext context, String zip)
	{
		getMendixObject().setValue(context, MemberNames.zip.toString(), zip);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return locationDetailsMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.locationDetails that = (myfirstmodule.proxies.locationDetails) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MyFirstModule.locationDetails";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
