// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class nameDetails
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject nameDetailsMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.nameDetails";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		title("title"),
		first("first"),
		last("last");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public nameDetails(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MyFirstModule.nameDetails"));
	}

	protected nameDetails(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject nameDetailsMendixObject)
	{
		if (nameDetailsMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MyFirstModule.nameDetails", nameDetailsMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MyFirstModule.nameDetails");

		this.nameDetailsMendixObject = nameDetailsMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'nameDetails.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static myfirstmodule.proxies.nameDetails initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.nameDetails.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static myfirstmodule.proxies.nameDetails initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.nameDetails(context, mendixObject);
	}

	public static myfirstmodule.proxies.nameDetails load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.nameDetails.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of title
	 */
	public final String gettitle()
	{
		return gettitle(getContext());
	}

	/**
	 * @param context
	 * @return value of title
	 */
	public final String gettitle(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.title.toString());
	}

	/**
	 * Set value of title
	 * @param title
	 */
	public final void settitle(String title)
	{
		settitle(getContext(), title);
	}

	/**
	 * Set value of title
	 * @param context
	 * @param title
	 */
	public final void settitle(com.mendix.systemwideinterfaces.core.IContext context, String title)
	{
		getMendixObject().setValue(context, MemberNames.title.toString(), title);
	}

	/**
	 * @return value of first
	 */
	public final String getfirst()
	{
		return getfirst(getContext());
	}

	/**
	 * @param context
	 * @return value of first
	 */
	public final String getfirst(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.first.toString());
	}

	/**
	 * Set value of first
	 * @param first
	 */
	public final void setfirst(String first)
	{
		setfirst(getContext(), first);
	}

	/**
	 * Set value of first
	 * @param context
	 * @param first
	 */
	public final void setfirst(com.mendix.systemwideinterfaces.core.IContext context, String first)
	{
		getMendixObject().setValue(context, MemberNames.first.toString(), first);
	}

	/**
	 * @return value of last
	 */
	public final String getlast()
	{
		return getlast(getContext());
	}

	/**
	 * @param context
	 * @return value of last
	 */
	public final String getlast(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.last.toString());
	}

	/**
	 * Set value of last
	 * @param last
	 */
	public final void setlast(String last)
	{
		setlast(getContext(), last);
	}

	/**
	 * Set value of last
	 * @param context
	 * @param last
	 */
	public final void setlast(com.mendix.systemwideinterfaces.core.IContext context, String last)
	{
		getMendixObject().setValue(context, MemberNames.last.toString(), last);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return nameDetailsMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.nameDetails that = (myfirstmodule.proxies.nameDetails) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MyFirstModule.nameDetails";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
