// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class NewUsers extends restservices.proxies.AnyObject
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.NewUsers";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		results("MyFirstModule.results");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public NewUsers(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MyFirstModule.NewUsers"));
	}

	protected NewUsers(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject newUsersMendixObject)
	{
		super(context, newUsersMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("MyFirstModule.NewUsers", newUsersMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MyFirstModule.NewUsers");
	}

	/**
	 * @deprecated Use 'NewUsers.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static myfirstmodule.proxies.NewUsers initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.NewUsers.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static myfirstmodule.proxies.NewUsers initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.NewUsers(context, mendixObject);
	}

	public static myfirstmodule.proxies.NewUsers load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.NewUsers.initialize(context, mendixObject);
	}

	/**
	 * @return value of results
	 */
	public final java.util.List<myfirstmodule.proxies.resultsParent> getresults() throws com.mendix.core.CoreException
	{
		return getresults(getContext());
	}

	/**
	 * @param context
	 * @return value of results
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<myfirstmodule.proxies.resultsParent> getresults(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<myfirstmodule.proxies.resultsParent> result = new java.util.ArrayList<myfirstmodule.proxies.resultsParent>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.results.toString());
		if (valueObject == null)
			return result;
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject))
			result.add(myfirstmodule.proxies.resultsParent.initialize(context, mendixObject));
		return result;
	}

	/**
	 * Set value of results
	 * @param results
	 */
	public final void setresults(java.util.List<myfirstmodule.proxies.resultsParent> results)
	{
		setresults(getContext(), results);
	}

	/**
	 * Set value of results
	 * @param context
	 * @param results
	 */
	public final void setresults(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<myfirstmodule.proxies.resultsParent> results)
	{
		java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier> identifiers = new java.util.ArrayList<com.mendix.systemwideinterfaces.core.IMendixIdentifier>();
		for (myfirstmodule.proxies.resultsParent proxyObject : results)
			identifiers.add(proxyObject.getMendixObject().getId());
		getMendixObject().setValue(context, MemberNames.results.toString(), identifiers);
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.NewUsers that = (myfirstmodule.proxies.NewUsers) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MyFirstModule.NewUsers";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Override
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
