// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class pictureDetails
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject pictureDetailsMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.pictureDetails";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		large("large"),
		medium("medium"),
		thumbnail("thumbnail");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public pictureDetails(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MyFirstModule.pictureDetails"));
	}

	protected pictureDetails(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject pictureDetailsMendixObject)
	{
		if (pictureDetailsMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MyFirstModule.pictureDetails", pictureDetailsMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MyFirstModule.pictureDetails");

		this.pictureDetailsMendixObject = pictureDetailsMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'pictureDetails.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static myfirstmodule.proxies.pictureDetails initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.pictureDetails.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static myfirstmodule.proxies.pictureDetails initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.pictureDetails(context, mendixObject);
	}

	public static myfirstmodule.proxies.pictureDetails load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.pictureDetails.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of large
	 */
	public final String getlarge()
	{
		return getlarge(getContext());
	}

	/**
	 * @param context
	 * @return value of large
	 */
	public final String getlarge(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.large.toString());
	}

	/**
	 * Set value of large
	 * @param large
	 */
	public final void setlarge(String large)
	{
		setlarge(getContext(), large);
	}

	/**
	 * Set value of large
	 * @param context
	 * @param large
	 */
	public final void setlarge(com.mendix.systemwideinterfaces.core.IContext context, String large)
	{
		getMendixObject().setValue(context, MemberNames.large.toString(), large);
	}

	/**
	 * @return value of medium
	 */
	public final String getmedium()
	{
		return getmedium(getContext());
	}

	/**
	 * @param context
	 * @return value of medium
	 */
	public final String getmedium(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.medium.toString());
	}

	/**
	 * Set value of medium
	 * @param medium
	 */
	public final void setmedium(String medium)
	{
		setmedium(getContext(), medium);
	}

	/**
	 * Set value of medium
	 * @param context
	 * @param medium
	 */
	public final void setmedium(com.mendix.systemwideinterfaces.core.IContext context, String medium)
	{
		getMendixObject().setValue(context, MemberNames.medium.toString(), medium);
	}

	/**
	 * @return value of thumbnail
	 */
	public final String getthumbnail()
	{
		return getthumbnail(getContext());
	}

	/**
	 * @param context
	 * @return value of thumbnail
	 */
	public final String getthumbnail(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.thumbnail.toString());
	}

	/**
	 * Set value of thumbnail
	 * @param thumbnail
	 */
	public final void setthumbnail(String thumbnail)
	{
		setthumbnail(getContext(), thumbnail);
	}

	/**
	 * Set value of thumbnail
	 * @param context
	 * @param thumbnail
	 */
	public final void setthumbnail(com.mendix.systemwideinterfaces.core.IContext context, String thumbnail)
	{
		getMendixObject().setValue(context, MemberNames.thumbnail.toString(), thumbnail);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return pictureDetailsMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.pictureDetails that = (myfirstmodule.proxies.pictureDetails) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MyFirstModule.pictureDetails";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
