// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package approntonotificationmodule.proxies;

public enum Enum_Layout
{
	top(new String[][] { new String[] { "en_US", "" }, new String[] { "nl_NL", "top" } }),
	topLeft(new String[][] { new String[] { "en_US", "" }, new String[] { "nl_NL", "topLeft" } }),
	topCenter(new String[][] { new String[] { "en_US", "" }, new String[] { "nl_NL", "topCenter" } }),
	topRight(new String[][] { new String[] { "en_US", "" }, new String[] { "nl_NL", "topRight" } }),
	center(new String[][] { new String[] { "en_US", "" }, new String[] { "nl_NL", "center" } }),
	centerLeft(new String[][] { new String[] { "en_US", "" }, new String[] { "nl_NL", "centerLeft" } }),
	centerRight(new String[][] { new String[] { "en_US", "" }, new String[] { "nl_NL", "centerRight" } }),
	bottom(new String[][] { new String[] { "en_US", "" }, new String[] { "nl_NL", "bottom" } }),
	bottomLeft(new String[][] { new String[] { "en_US", "" }, new String[] { "nl_NL", "bottomLeft" } }),
	bottomCenter(new String[][] { new String[] { "en_US", "" }, new String[] { "nl_NL", "bottomCenter" } }),
	bottomRight(new String[][] { new String[] { "en_US", "" }, new String[] { "nl_NL", "bottomRight" } });

	private java.util.Map<String,String> captions;

	private Enum_Layout(String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<String,String>();
		for (String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public String getCaption(String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public String getCaption()
	{
		return captions.get("en_US");
	}
}
