// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package approntonotificationmodule.proxies;

public enum Enum_NotificationType
{
	error(new String[][] { new String[] { "en_US", "" }, new String[] { "nl_NL", "error" } }),
	warning(new String[][] { new String[] { "en_US", "" }, new String[] { "nl_NL", "warning" } }),
	info(new String[][] { new String[] { "en_US", "" }, new String[] { "nl_NL", "info" } }),
	success(new String[][] { new String[] { "en_US", "" }, new String[] { "nl_NL", "success" } }),
	alert(new String[][] { new String[] { "en_US", "" }, new String[] { "nl_NL", "alert" } });

	private java.util.Map<String,String> captions;

	private Enum_NotificationType(String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<String,String>();
		for (String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public String getCaption(String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public String getCaption()
	{
		return captions.get("en_US");
	}
}
