// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package restservices.proxies;

public class DataSyncState
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject dataSyncStateMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "RestServices.DataSyncState";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		CollectionUrl("CollectionUrl"),
		SequenceNr("SequenceNr"),
		Status("Status");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public DataSyncState(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "RestServices.DataSyncState"));
	}

	protected DataSyncState(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject dataSyncStateMendixObject)
	{
		if (dataSyncStateMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("RestServices.DataSyncState", dataSyncStateMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a RestServices.DataSyncState");

		this.dataSyncStateMendixObject = dataSyncStateMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'DataSyncState.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static restservices.proxies.DataSyncState initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return restservices.proxies.DataSyncState.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static restservices.proxies.DataSyncState initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new restservices.proxies.DataSyncState(context, mendixObject);
	}

	public static restservices.proxies.DataSyncState load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return restservices.proxies.DataSyncState.initialize(context, mendixObject);
	}

	public static java.util.List<restservices.proxies.DataSyncState> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<restservices.proxies.DataSyncState> result = new java.util.ArrayList<restservices.proxies.DataSyncState>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//RestServices.DataSyncState" + xpathConstraint))
			result.add(restservices.proxies.DataSyncState.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of CollectionUrl
	 */
	public final String getCollectionUrl()
	{
		return getCollectionUrl(getContext());
	}

	/**
	 * @param context
	 * @return value of CollectionUrl
	 */
	public final String getCollectionUrl(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.CollectionUrl.toString());
	}

	/**
	 * Set value of CollectionUrl
	 * @param collectionurl
	 */
	public final void setCollectionUrl(String collectionurl)
	{
		setCollectionUrl(getContext(), collectionurl);
	}

	/**
	 * Set value of CollectionUrl
	 * @param context
	 * @param collectionurl
	 */
	public final void setCollectionUrl(com.mendix.systemwideinterfaces.core.IContext context, String collectionurl)
	{
		getMendixObject().setValue(context, MemberNames.CollectionUrl.toString(), collectionurl);
	}

	/**
	 * @return value of SequenceNr
	 */
	public final Long getSequenceNr()
	{
		return getSequenceNr(getContext());
	}

	/**
	 * @param context
	 * @return value of SequenceNr
	 */
	public final Long getSequenceNr(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (Long) getMendixObject().getValue(context, MemberNames.SequenceNr.toString());
	}

	/**
	 * Set value of SequenceNr
	 * @param sequencenr
	 */
	public final void setSequenceNr(Long sequencenr)
	{
		setSequenceNr(getContext(), sequencenr);
	}

	/**
	 * Set value of SequenceNr
	 * @param context
	 * @param sequencenr
	 */
	public final void setSequenceNr(com.mendix.systemwideinterfaces.core.IContext context, Long sequencenr)
	{
		getMendixObject().setValue(context, MemberNames.SequenceNr.toString(), sequencenr);
	}

	/**
	 * Set value of Status
	 * @param status
	 */
	public final restservices.proxies.TrackingState getStatus()
	{
		return getStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of Status
	 */
	public final restservices.proxies.TrackingState getStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Status.toString());
		if (obj == null)
			return null;

		return restservices.proxies.TrackingState.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Status
	 * @param status
	 */
	public final void setStatus(restservices.proxies.TrackingState status)
	{
		setStatus(getContext(), status);
	}

	/**
	 * Set value of Status
	 * @param context
	 * @param status
	 */
	public final void setStatus(com.mendix.systemwideinterfaces.core.IContext context, restservices.proxies.TrackingState status)
	{
		if (status != null)
			getMendixObject().setValue(context, MemberNames.Status.toString(), status.toString());
		else
			getMendixObject().setValue(context, MemberNames.Status.toString(), null);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return dataSyncStateMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final restservices.proxies.DataSyncState that = (restservices.proxies.DataSyncState) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "RestServices.DataSyncState";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
