// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package restservices.proxies;

public enum ResponseCode
{
	OK(new String[][] { new String[] { "en_US", "OK" }, new String[] { "nl_NL", "OK" } }),
	NotModified(new String[][] { new String[] { "en_US", "Not Modified" }, new String[] { "nl_NL", "NotModified" } }),
	Error(new String[][] { new String[] { "en_US", "Error" }, new String[] { "nl_NL", "Error" } });

	private java.util.Map<String,String> captions;

	private ResponseCode(String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<String,String>();
		for (String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public String getCaption(String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public String getCaption()
	{
		return captions.get("en_US");
	}
}
